### ISSUE TITLE
"Please review my Garden Plan" posting to r/vegetablegardening

### ISSUE THREAD

**Issue by philipmjohnson** [agilegardenclub/agilegardenclub.github.io#10]
I think it would be really interesting to create a mockup page that illustrates Jenna's upcoming garden in GardenBud form.  

Assume it's displayed on a large iPad so that the entire season would be visible without scrolling.  

Then, post it to the reddit group for comments.. This would be an interesting experiment to see what people's replies would be. 

We don't have to say this is a mockup, we can just ask for comments on the plan like any other gardener. It would be interesting to see what the quality of responses would be---would the comments be better because the plan representation is higher quality? Would some folks say, "What app did you use to generate your plan?" etc.

**Comment by Jennacd** [comment]
https://www.reddit.com/r/vegetablegardening/comments/sugnmk/feedback_on_garden_plans_please/
